amoad/amoad-ios-sdk

Documents/Native/Guide_nativeApp.asciidoc
Modules/AMoAdNativeView.h
README.asciidoc

広告の取得に失敗した時のコールバック関数を指定できるようになりました。

Native_addFailureCallback

---

Modules/AMoAdNativeView.h
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/Base.lproj/Main.storyboard
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/ViewController.m

3.1.0 beta 3
不要な広告をクリアする関数を追加しました。
既存のViewに広告をレンダリングする関数を追加しました。
ネイティブ（App）アイコン＋テキストのサンプルを修正しました。

NativeBeta3_addIconTextSample

---

Documents/Native/Guide_nativeApp.asciidoc
README.asciidoc

Native310Beta3_addDocuments

---

Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/ViewController.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText.xcodeproj/project.pbxproj
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AdIconTextTableViewCell.xib
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AppDelegate.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AppDelegate.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/Base.lproj/Main.storyboard
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/Info.plist
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/UserTableViewCell.xib
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/ViewController.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/ViewController.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/main.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconTextTests/AMoAdNativeListViewIconTextTests.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconTextTests/Info.plist

リストビュー、アイコン＋テキストのサンプルアプリを追加しました。

NativeView_addListViewSample

---

Modules/AMoAdNativeView.h

Native310beta3

---

README.asciidoc

Native_removeStagingBuild

---

Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText.xcodeproj/project.pbxproj
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AdImageTextTableViewCell.xib
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AppDelegate.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AppDelegate.m
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/Base.lproj/Main.storyboard
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/Info.plist
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/UserTableViewCell.xib
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/ViewController.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/ViewController.m
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/main.m
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageTextTests/AMoAdNativeListViewImageTextTests.m
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageTextTests/Info.plist

リストビュー型メイン画像＋テキストのサンプルを追加しました。

NativeSample_addListViewImageText

---

Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText.xcodeproj/project.pbxproj
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AdImageTextView.xib
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AppDelegate.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AppDelegate.m
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/Base.lproj/Main.storyboard
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/Info.plist
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/ViewController.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/ViewController.m
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/main.m
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageTextTests/AMoAdNativeAppImageTextTests.m
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageTextTests/Info.plist

ネイティブApp、メイン画像＋テキストのサンプルコードを追加しました。

NativeSample_AMoAdNativeAppImageText

---

Samples/AMoAdNativeListViewText/AMoAdNativeListViewText.xcodeproj/project.pbxproj
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AdTextTableViewCell.xib
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AppDelegate.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AppDelegate.m
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/Base.lproj/Main.storyboard
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/Info.plist
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/UserTableViewCell.xib
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/ViewController.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/ViewController.m
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/main.m
Samples/AMoAdNativeListViewText/AMoAdNativeListViewTextTests/AMoAdNativeListViewTextTests.m
Samples/AMoAdNativeListViewText/AMoAdNativeListViewTextTests/Info.plist

@hashikell 
一行テキストサンプルの作成
本番用sidで広告が表示されることを確認しました。

NativeListViewTextSample

---

Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/ViewController.m

NativeGarbledCharacters

---

Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/Base.lproj/Main.storyboard
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/ViewController.m

@hashikell 
renderAdのコード追加
レビュ＆マージをお願いします。

NativeAppIconTestSample

---

Samples/AMoAdNativeAppText/AMoAdNativeAppText.xcodeproj/project.pbxproj
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AdTextView.xib
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AppDelegate.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AppDelegate.m
Samples/AMoAdNativeAppText/AMoAdNativeAppText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeAppText/AMoAdNativeAppText/Base.lproj/Main.storyboard
Samples/AMoAdNativeAppText/AMoAdNativeAppText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeAppText/AMoAdNativeAppText/Info.plist
Samples/AMoAdNativeAppText/AMoAdNativeAppText/ViewController.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/ViewController.m
Samples/AMoAdNativeAppText/AMoAdNativeAppText/main.m
Samples/AMoAdNativeAppText/AMoAdNativeAppTextTests/AMoAdNativeAppTextTests.m
Samples/AMoAdNativeAppText/AMoAdNativeAppTextTests/Info.plist

@hashikell 
ネイティブAPP型の一行テキストのサンプル作成
本番sidで表示確認済です。

NativeAppTextSample

---

Modules/AMoAdNativeView.h
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h

NativeView_customLinkUrl

---

Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink.xcodeproj/project.pbxproj
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AdIconTextLinkView.xib
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AppDelegate.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AppDelegate.m
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/Base.lproj/Main.storyboard
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/Info.plist
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/ViewController.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/ViewController.m
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/main.m
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLinkTests/AMoAdNativeAppIconTextLinkTests.m
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLinkTests/Info.plist

リンクViewを指定するサンプルコード（ネイティブApp、アイコン＋テキスト）を追加しました。

NativeSample_addNativeAppIconTextLink

---

Documents/Native/Guide_nativeApp.asciidoc
Modules/AMoAdNativeView.h
README.asciidoc
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/ViewController.m
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AdImageTextView.xib
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AppDelegate.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AppDelegate.m
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/Base.lproj/Main.storyboard
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/Info.plist
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/ViewController.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/ViewController.m
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/main.m
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageTextCoder.xcodeproj/project.pbxproj
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageTextTests/AMoAdNativeAppImageTextTests.m
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageTextTests/Info.plist
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/ViewController.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/ViewController.m

NativeView_addCoder

---

Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Modules/AMoAdNativeView.h
README.asciidoc
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h

広告のタップ回数（ダブルクリックの場合は「2」）を指定できるようになりました。

NativeViewCoder_numberOfTapsRequired

---

Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
README.asciidoc

App Storeモーダル遷移機能のクリック処理を安定化しました。

NativeDirectStore_improveClick

---

Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText.xcodeproj/project.pbxproj
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdLogger.h
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AdImageTextCollectionViewCell.xib
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AppDelegate.h
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AppDelegate.m
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/Base.lproj/LaunchScreen.xib
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/Base.lproj/Main.storyboard
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/Images.xcassets/AppIcon.appiconset/Contents.json
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/Info.plist
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/UserCollectionViewCell.xib
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/ViewController.h
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/ViewController.m
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/main.m

UICollectionViewのサンプルアプリを追加しました。

NativeSample_AMoAdNativeCollectionViewImageText_init

---

Modules/AMoAdNativeView.h
README.asciidoc
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h

Native_advertisingTrackingEnabled

---

Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
README.asciidoc

ドキュメントに目次をつけました。
更新履歴はreleasesを参照することとしました。

NativeDocument_addTableOfContents

---

Documents/Native/Guide_listView.asciidoc
README.asciidoc

ドキュメントのSDKバージョンが古い箇所を更新しました。
トップページのレイアウトを変更しました。

NativeDocument_fixVersion

---

Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Modules/AMoAdNativeView.h
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconText/AMoAdNativeAppIconText/ViewController.m
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/ViewController.m
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageText/AMoAdNativeAppImageText/ViewController.m
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/ViewController.m
Samples/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeAppText/AMoAdNativeAppText/ViewController.m
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/ViewController.m
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/ViewController.m
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/ViewController.m
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h
Samples/AMoAdNativeListViewText/AMoAdNativeListViewText/ViewController.m

Native_enhance_DelegateReceive

---

README.asciidoc

READMEのバージョン番号が古かったので修正しました（→ 3.6.2）。

Native_fix_ReadmeSdkVer

---

README.asciidoc

Document_addBanner_fixLink

---

README.asciidoc

「ダウンロードモジュール」タイトルに番号を振らないように修正しました。

Document_fix_downloadTitle

---

Documents/UnityPlugin/Guide.asciidoc
README.asciidoc

BannerUnityPlugin_fix_DocumentLink

---

Documents/UnityPlugin/Guide.asciidoc

BannerUnityPlugin_updateDocument

---

Documents/UnityPlugin/Guide.asciidoc

UnityプラグインのドキュメントにAndroid用パラメタを追加しました。

BannerUnityPlugin_add_androidParam

---

Documents/UnityPlugin/Guide.asciidoc

UnityプラグインのドキュメントにAndroid用Tipを追加しました。

BannerUnityPlugin_add_androidParamTips

---

Modules/AMoAdAnalytics.h
Modules/AMoAdNativePreRoll.h

NativePreRoll_beta

---

Documents/Cocos2dxModule/Display.asciidoc
Documents/Cocos2dxModule/Guide.asciidoc
Documents/Cocos2dxModule/Interstitial.asciidoc
Documents/Interstitial/Guide.asciidoc
Documents/UnityPlugin/Guide.asciidoc
README.asciidoc

Cocos2dx_addDocuments

---

Documents/Display/Interstitial.asciidoc
README.asciidoc

インタースティシャル広告をSDKから直接、使用するドキュメントを追加しました。

Interstitial_addSdkDocuments

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
README.asciidoc

SdkVer_3_9_3

---

README.asciidoc
WebView/guide.md

WebView実装ガイドを追加しました。
iOS/AndroidのWebViewにAMoAdアドタグ（JavaScript）を貼るためのガイドです。

WebView_init

---

Documents/Display/Guide.asciidoc

fixAMoAdDisplayDocument

---

Modules/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeCollectionViewIconText/AMoAdNativeCollectionViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeCollectionViewText/AMoAdNativeCollectionViewText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h

[NATIVE] 広告テンプレートをリソース名ではなくリソースオブジェクトで指定するI/Fを追加しました。

NativeView_nibParam

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
Documents/Native/Overview_nativeApp.asciidoc
Modules/AMoAdNativeView.h
README.asciidoc

- 対応端末・OSを更新しました
- ネイティブ広告テンプレートをNibオブジェクト指定できるようになったドキュメントを書きました

Document_updateTarget_useNib

---

Samples/Display/AMoAdSample/AMoAdSample/AMoAdNativeView.h
Samples/DisplayInterstitial/AMoAdInterstitialAdSample/AMoAdInterstitialAdSample/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeCollectionViewIconText/AMoAdNativeCollectionViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeCollectionViewText/AMoAdNativeCollectionViewText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeView.h
Samples/Native/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeView.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdNativeView.h

公開ヘッダのコメントを修正しました（nibName -> nib）。

NativeView_fixHeaderCommentNib

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
README.asciidoc

v3.9.6
1. バックグラウンドスレッドからの呼び出しに対応しました
2. 端末スペック情報を利用した配信に対応しました

v3_9_6_bgThreadCall_DeviceSpecTargeting

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
README.asciidoc

v3_9_7_updateDocumentVers

---

Documents/UnityPlugin/Guide.asciidoc

UnityプラグインがUnityバージョン5.3.0に対応しました。

Document_Unity_Version

---

Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample.xcodeproj/project.pbxproj
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAd.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdLogger.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdWeb.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AppDelegate.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AppDelegate.m
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/Assets.xcassets/AppIcon.appiconset/Contents.json
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/Assets.xcassets/Brand Assets.launchimage/Contents.json
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/Assets.xcassets/Contents.json
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/Base.lproj/LaunchScreen.storyboard
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/Base.lproj/Main.storyboard
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/Info.plist
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/ViewController.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/ViewController.m
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/index.html
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/main.m

SampleWebView_init

---

Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample.xcodeproj/project.pbxproj
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AMoAdSdk/AMoAd.h
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AMoAdSdk/AMoAdLogger.h
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AMoAdSdk/AMoAdWeb.h
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample-Bridging-Header.h
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AppDelegate.swift
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/Assets.xcassets/AppIcon.appiconset/Contents.json
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/Assets.xcassets/Brand Assets.launchimage/Contents.json
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/Assets.xcassets/Contents.json
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/Base.lproj/LaunchScreen.storyboard
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/Base.lproj/Main.storyboard
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/Info.plist
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/ViewController.swift
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/index.html

SampleWebViewSwift_init

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
Documents/WebView/guide.md
README.asciidoc

Document_addWebViewSdk

---

Modules/AMoAdLogger.h
Modules/AMoAdWeb.h
Samples/Display/AMoAdSample/AMoAdSample/AMoAdLogger.h
Samples/Display/AMoAdSample/AMoAdSample/AMoAdWeb.h
Samples/DisplayInterstitial/AMoAdInterstitialAdSample/AMoAdInterstitialAdSample/AMoAdLogger.h
Samples/DisplayInterstitial/AMoAdInterstitialAdSample/AMoAdInterstitialAdSample/AMoAdWeb.h
Samples/Native/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeCollectionViewIconText/AMoAdNativeCollectionViewIconText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeCollectionViewIconText/AMoAdNativeCollectionViewIconText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeCollectionViewText/AMoAdNativeCollectionViewText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeCollectionViewText/AMoAdNativeCollectionViewText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdWeb.h
Samples/Native/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdLogger.h
Samples/Native/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdWeb.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdLogger.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdWeb.h

Web_addModule

---

WebView/guide.md

WebViewManualForAndroid

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
README.asciidoc

v4.1.1
端末指定配信を行うため、広告リクエストに端末モデル名を送信するよう変更しました。

AdCall_addSendHwMac

---

Documents/UnityPlugin/Interstitial.asciidoc
Samples/UnityPlugin/AMoAdUnityPluginInterstitialSample/Assets/Scripts/AMoAdUnityPluginInterstitialSample.cs

@hashikell 
UnityのInterstitial広告サンプルの修正
- Unityサンプルアプリのコード修正
- Unityマニュアルのサンプルコード修正
サンプルアプリの動作確認済みです。

UnityPluginSampleFix

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
README.asciidoc

バナー広告のスレッド処理を改善しました。
* 複数スレッドからの呼び出しに同期オブジェクトで対応しました
* バックグラウンドから広告Viewを生成された時のUser-Agentの取得が確実に広告リクエスト前になるよう修正しました

Banner_improveThread

---

README.asciidoc

ネイティブHTML広告のドキュメント（リンク）を追加しました。

addNativeHTMLDoc

---

Documents/Display/Guide.asciidoc
Documents/Display/Interstitial.asciidoc
Documents/Install/Install.asciidoc
Documents/Native/Guide_listView.asciidoc
Documents/Native/Guide_nativeApp.asciidoc
Documents/Native/Guide_preroll.asciidoc
README.asciidoc

Xcode 7より、varディレクトリへアクセスする警告が表示されていたのを修正しました。

SuppressVarWarning

---

Documents/UnityPlugin/Interstitial.asciidoc

@hashikell 
- SetInterstitialPortraitPanel()の追記
- SetInterstitialLandscapePanel ()の追記
- SetInterstitialDisplayClickable ()の追記
- SetInterstitialDialogShown ()の追記

UnityPluginInterstitialManualFix

---

Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdAnalytics.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdInterstitial.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdLogger.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdNativeView.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdView.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdWeb.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdAnalytics.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdInterstitial.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdLogger.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdNativePreRoll.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdNativeView.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdView.h

NativeApp_improveClick

---

README.asciidoc

インタースティシャル広告の16:9動画の表示レイアウトを改善しました。

InterstitialWideVideoSupport

---

README.asciidoc

v4_7_0_Documents

---

Modules/AMoAd.h
Samples/Display/AMoAdSample/AMoAdSample/AMoAd.h
Samples/DisplayInterstitial/AMoAdInterstitialDemo/AMoAdInterstitialDemo/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeCollectionViewIconText/AMoAdNativeCollectionViewIconText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeCollectionViewText/AMoAdNativeCollectionViewText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAd.h
Samples/Native/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAd.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAd.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAd.h
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AMoAdSdk/AMoAd.h

AMoAd.hにFoundation.hをimportし忘れていたのを修正しました。

addFoundationHeaderToAMoAd_h

---

README.asciidoc

- PreRollのvimpクエリにAnalyticsとtagを追加しました
- PreRollのvimp URLが間違っていたのを修正しました

appendAnalyticsToPreRollVimpUrl

---

Modules/AMoAdNativeMainVideoView.h
README.asciidoc
Samples/Display/AMoAdSample/AMoAdSample/AMoAdNativeMainVideoView.h
Samples/DisplayInterstitial/AMoAdInterstitialDemo/AMoAdInterstitialDemo/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeAppIconText/AMoAdNativeAppIconText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeAppIconTextLink/AMoAdNativeAppIconTextLink/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeAppImageText/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeAppImageTextCoder/AMoAdNativeAppImageText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeAppText/AMoAdNativeAppText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeCollectionViewIconText/AMoAdNativeCollectionViewIconText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeCollectionViewImageText/AMoAdNativeCollectionViewImageText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeCollectionViewText/AMoAdNativeCollectionViewText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeListViewIconText/AMoAdNativeListViewIconText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeListViewImageText/AMoAdNativeListViewImageText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Native/AMoAdNativeListViewText/AMoAdNativeListViewText/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/NativePreRoll/AMoAdNativePreRoll/AMoAdNativePreRoll/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/Swift/AMoAdSwift/AMoAdSwift/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/WebView/AMoAdWebViewSample/AMoAdWebViewSample/AMoAdSdk/AMoAdNativeMainVideoView.h
Samples/WebView/AMoAdWebViewSwiftSample/AMoAdWebViewSwiftSample/AMoAdSdk/AMoAdNativeMainVideoView.h

Add InFeed AfiO

---

README.asciidoc

InFeed AfiO: Auto play / Rewind on pause / Out view

---

README.asciidoc

インフィード AfiO 広告機能の軽微な不具合を修正しました。

Fix some bugs in InFeed AfiO

---

AMoAdSdkDemo/AMoAdSdkDemo.xcodeproj/project.pbxproj
AMoAdSdkDemo/AMoAdSdkDemo/AMoAdSdk/AMoAdInterstitialVideo.h
AMoAdSdkDemo/AMoAdSdkDemo/AMoAdSdkDemo-Bridging-Header.h
AMoAdSdkDemo/AMoAdSdkDemo/InterstitialAfiO/InterstitialAfio.storyboard
AMoAdSdkDemo/AMoAdSdkDemo/InterstitialAfiO/InterstitialAfioViewController.swift
AMoAdSdkDemo/AMoAdSdkDemo/ViewController.swift
Modules/AMoAdInterstitialVideo.h
README.asciidoc

インタースティシャル AfiO 広告配信機能に対応しました。

Add Interstitial AfiO

---

README.asciidoc

Fix readme

---

AMoAdSdkDemo/AMoAdSdkDemo.xcodeproj/project.pbxproj
AMoAdSdkDemo/AMoAdSdkDemo/AdMobBannerAdController.swift
AMoAdSdkDemo/AMoAdSdkDemo/AdMobRewardedAdViewController.swift
AMoAdSdkDemo/AMoAdSdkDemo/Base.lproj/Main.storyboard
AMoAdSdkDemo/AMoAdSdkDemo/Info.plist
AMoAdSdkDemo/AMoAdSdkDemo/MainTableSource.json
AMoAdSdkDemo/AMoAdSdkDemo/MasterViewController.swift
AMoAdSdkDemo/AMoAdSdkDemo/MaxInterstitialAdViewController.swift
AMoAdSdkDemo/AMoAdSdkDemo/MaxMrecAdViewController.swift
AMoAdSdkDemo/AMoAdSdkDemo/MaxRewardedAdViewController.swift
AMoAdSdkDemo/Podfile

- サンプルアプリにMax、Admobメディエーションを活用した広告配信用の項目を追加

Max、Admobメディエーションのサンプルコードを追加
